### ISSUE TITLE
Test Example doesn't work. 

### ISSUE THREAD

**Issue by Schizo** [harabchuk/kibana-dashboard-api#1]
Just wanted to give a quick try, my elasticsearch and Kibana is running and i am already successfully using the elasticsearch python api. 

Anyway i get the error: 
NameError: name 'VisualizationsManager' is not defined

```python
from kibana_dashboard_api import Visualizations, Dashboards
from elasticsearch import Elasticsearch

es_connection = Elasticsearch(hosts=['http://login:pass@localhost:9200/'])

visualizations = VisualizationsManager(es_connection)
```

**Comment by harabchuk** [comment]
There was a bug in the example, you should import VisualizationsManager and DashboardsManager instead of Visualizations, Dashboards
```python
from kibana_dashboard_api import VisualizationsManager, DashboardsManager
```
